name: Build Arcalm ISO with Calamares

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm git base-devel archiso cmake extra-cmake-modules \
            yaml-cpp hwinfo efibootmgr gtk-update-icon-cache libpwquality squashfs-tools \
            rsync mtools xorriso mkinitcpio-nfs-utils dosfstools grub qt5-tools \
            qt5-svg qt5-xmlpatterns qt5-base qt5-declarative qt5-quickcontrols qt5-graphicaleffects \
            qt5-webengine qt5-webchannel qt5-location qt5-sensors qt5-translations \
            qt5-websockets qt5-x11extras qt5-imageformats qt5-multimedia qt5-serialport \
            kpmcore qt6-base python-pyqt5 polkit-qt5 kcoreaddons kconfig ki18n

      - name: Create build user
        run: |
          useradd -m builduser
          echo "builduser ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          mkdir -p /home/builduser/.gnupg
          chown -R builduser:builduser /home/builduser

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Clone Calamares and build it
        run: |
          # Use official release tag instead of non-existent branch
          git clone https://github.com/calamares/calamares.git /home/builduser/calamares
          chown -R builduser:builduser /home/builduser/calamares
          sudo -u builduser bash -c '
            cd /home/builduser/calamares && mkdir -p build && cd build
            cmake .. -DCMAKE_INSTALL_PREFIX=/usr
            make -j$(nproc)
            sudo make install
          '

      - name: Prepare ISO build environment
        run: |
          cp -r /usr/share/archiso/configs/releng/ arcalmiso
          cd arcalmiso
          sed -i 's|Arch Linux|arcalm|g' ./airootfs/etc/issue
          sed -i 's|Arch Linux|arcalm|g' ./airootfs/etc/motd
          sed -i 's|Arch Linux|arcalm|g' ./airootfs/etc/os-release
          echo 'arcalm' > ./airootfs/etc/hostname

          # Create autostart file for Calamares
          mkdir -p ./airootfs/etc/skel/.config/autostart
          cat <<EOF > ./airootfs/etc/skel/.config/autostart/calamares.desktop
          [Desktop Entry]
          Type=Application
          Name=Calamares Installer
          Exec=calamares
          Icon=calamares
          X-GNOME-Autostart-enabled=true
          EOF


          mkdir -p ./airootfs/etc/calamares/branding/arcalm
          cp /home/builduser/calamares/calamares/settings.conf ./airootfs/etc/calamares/
          cp /home/builduser/calamares/calamares/branding/example/branding.desc ./airootfs/etc/calamares/branding/arcalm/

      - name: Build ISO
        run: |
          cd arcalmiso
          mkarchiso -v . out

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: arcalm-linux-iso
          path: arcalmiso/out/*.iso
